### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by abrahamnunes**
I fixed some of the documentation errors. 

Note that if we update the documentation, there will be errors in the `fitr.py` and `loglik_functions.py` modules due to the relative import of the `utils.py` module. To compile the documentation without error, simply remove the `.` in front of `.utils` in the imports. Then once the documentation is built, replace the period or else the build will break.

### CODE REVIEW

**Comment by abrahamnunes** [comment]
Should be ready to merge now.

**Comment by ARudiuk** [comment]
Are the docs not being built from the latest version? Instead of the complied doc? 

Or am I missing something?

**Comment by abrahamnunes** [comment]
Perhaps I'm doing this wrong, but I compiled them locally with Sphinx. The
compiled pages are in the "build" folder.



Abraham Nunes

Resident Physician
Department of Psychiatry
Dalhousie University
Halifax, NS, Canada
Tel: (902) 292-8297
Email: nunes@dal.ca

**Comment by ARudiuk** [comment]
I'm not sure if this will work, but I want to see what happens so i'm merging!

**Pull request merged**
